# Generated by Django 4.0.3 on 2022-03-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=10)),
                ('emailId', models.EmailField(max_length=254)),
                ('CompanyCode', models.IntegerField(unique=True)),
                ('Strength', models.IntegerField(max_length=10)),
                ('webSite', models.CharField(max_length=10)),
                ('createdTime', models.TimeField(max_length=10)),
            ],
        ),
    ]
