# Generated by Django 4.0.3 on 2022-03-18 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inncomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='createdTime',
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyCode',
            field=models.CharField(blank=True, max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='Strength',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='emailId',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='webSite',
            field=models.URLField(blank=True),
        ),
    ]
