# Generated by Django 4.0.3 on 2022-03-18 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inncomapp', '0003_company_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyCode',
            field=models.CharField(blank=True, max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('[a-zA-Z]{2}[0-9]{2}(N|E)', '1st & 2nd characters should be alphabets')]),
        ),
    ]
